name: 'File Copy'
description: 'Pretends to copy some files and return the number of files copied'
inputs:
  Token:
    description: 'GitHub API Token'
    required: true
  Header: 
    description: 'Header to be added along with the request'
    required: true
  RequestBody: 
    description: 'Request Body for the api call'
    required: true
  ExpectedOutput:
    description: 'Output to compare the api response with'
    required: true
outputs:
  comparisonoutput:
    description: 'Script to fail/Pass based on the api call script'
runs:
  using: "composite"
  steps: 
    - run: |
       ${{ github.action_path }}/apicalltest.ps1 -token ${{inputs.API_TOKEN}} -Header ${{ inputs.Header }} -RequestBody ${{ inputs.RequestBody }} -ExpectedOutput ${{ inputs.ExpectedOutput }}
      shell: pwsh
